apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-example
spec:
  containers:
  - name: gpu-container
    image: tensorflow/tensorflow:latest-gpu
    command: ["sleep", "21600"]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /testvol
      name: testvol
  restartPolicy: Never
  volumes:
    - name: testvol
      persistentVolumeClaim:
        claimName: testvol